FROM node:20.9.0-alpine as build
WORKDIR /build
COPY ./back .
RUN npm i -g pnpm
RUN npm i -g prisma@5.5.2
RUN pnpm i && \
  npx prisma migrate deploy --schema=./prisma/schema.prisma && \
  pnpm build:prod



FROM build

WORKDIR /app

COPY --from=build /build/dist .

RUN npm i -g prisma@5.5.2

EXPOSE 3000

CMD ["node", "index.js"]
