FROM node:20.9.0-alpine as build
WORKDIR /build
COPY ./front .
RUN corepack enable
RUN pnpm i --frozen-lockfile && \
  pnpm build && \
  echo '{"type": "module"}' > /build/build/package.json 



FROM build
WORKDIR /app
COPY --from=build /build/build .

ENV PORT=4000
EXPOSE 4000

CMD ["node", "index.js"]
